USE [master]
GO

/****** Object:  Database [InventMgm]    Script Date: 27-06-2017 03:46:37 PM ******/
CREATE DATABASE [InventMgm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventMgm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\InventMgm.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InventMgm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\InventMgm_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [InventMgm] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventMgm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventMgm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventMgm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventMgm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventMgm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventMgm] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventMgm] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [InventMgm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventMgm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventMgm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventMgm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventMgm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventMgm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventMgm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventMgm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventMgm] SET  ENABLE_BROKER 
GO

ALTER DATABASE [InventMgm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventMgm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventMgm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventMgm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventMgm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventMgm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventMgm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventMgm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InventMgm] SET  MULTI_USER 
GO

ALTER DATABASE [InventMgm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventMgm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventMgm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventMgm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [InventMgm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventMgm] SET  READ_WRITE 
GO

